//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BILHETERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_BILHETERIA()
        {
            this.TB_MENSAGEM_ANCINE = new HashSet<TB_MENSAGEM_ANCINE>();
            this.TB_SESSAO_ANCINE = new HashSet<TB_SESSAO_ANCINE>();
        }
    
        public long BIL_ID { get; set; }
        public string EMP_CD_ANCINE { get; set; }
        public string SAL_CD_ANCINE { get; set; }
        public System.DateTime BIL_DIA_CIN { get; set; }
        public string BIL_HOUVE_SES { get; set; }
        public string BIL_RETIF { get; set; }
        public string BIL_PROT { get; set; }
        public string BIL_ADIMP_SALA { get; set; }
        public string BIL_STATUS_PROT { get; set; }
    
        public virtual TB_EMPRESA_COMPLEXO TB_EMPRESA_COMPLEXO { get; set; }
        public virtual TB_EMPRESA_COMPLEXO TB_EMPRESA_COMPLEXO1 { get; set; }
        public virtual TB_EMPRESA_COMPLEXO TB_EMPRESA_COMPLEXO2 { get; set; }
        public virtual TB_SALA TB_SALA { get; set; }
        public virtual TB_SALA TB_SALA1 { get; set; }
        public virtual TB_SALA TB_SALA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MENSAGEM_ANCINE> TB_MENSAGEM_ANCINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SESSAO_ANCINE> TB_SESSAO_ANCINE { get; set; }
    }
}
