//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DISTRIBUIDORA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DISTRIBUIDORA()
        {
            this.TB_FILME = new HashSet<TB_FILME>();
        }
    
        public long DIS_CNPJ { get; set; }
        public string DIS_NM { get; set; }
        public string DIS_CD_AUX { get; set; }
        public Nullable<System.DateTime> DIS_DT_INC { get; set; }
        public Nullable<System.DateTime> DIS_DT_ALT { get; set; }
        public Nullable<System.DateTime> DIS_DT_DES { get; set; }
        public string DIS_MOT_DES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_FILME> TB_FILME { get; set; }
    }
}
