//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPRESA_COMPLEXO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EMPRESA_COMPLEXO()
        {
            this.TB_BILHETERIA = new HashSet<TB_BILHETERIA>();
            this.TB_BILHETERIA1 = new HashSet<TB_BILHETERIA>();
            this.TB_BILHETERIA2 = new HashSet<TB_BILHETERIA>();
            this.TB_GRP_CIN = new HashSet<TB_GRP_CIN>();
            this.TB_PROGRAMA = new HashSet<TB_PROGRAMA>();
            this.TB_SALA = new HashSet<TB_SALA>();
            this.TB_VENDEDOR_REMOTO = new HashSet<TB_VENDEDOR_REMOTO>();
        }
    
        public string EMP_CD_ANCINE { get; set; }
        public string EMP_RZ_SOCIAL { get; set; }
        public string EMP_NM_FANT { get; set; }
        public string EMP_CNPJ { get; set; }
        public string EMP_INSCRICAO { get; set; }
        public string EMP_END { get; set; }
        public Nullable<int> EMP_NUM_END { get; set; }
        public string EMP_CMP_END { get; set; }
        public string EMP_BRR_END { get; set; }
        public string EMP_CID_END { get; set; }
        public Nullable<int> EMP_TEL_DDD { get; set; }
        public Nullable<int> EMP_TEL { get; set; }
        public string EMP_UF_END { get; set; }
        public string EMP_CEP_END { get; set; }
        public string EMP_CD_AUX { get; set; }
        public Nullable<System.DateTime> EMP_DT_INC { get; set; }
        public Nullable<System.DateTime> EMP_DT_ALT { get; set; }
        public Nullable<System.DateTime> EMP_DT_DES { get; set; }
        public string EMP_MOT_DES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BILHETERIA> TB_BILHETERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BILHETERIA> TB_BILHETERIA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BILHETERIA> TB_BILHETERIA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_GRP_CIN> TB_GRP_CIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMA> TB_PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SALA> TB_SALA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_VENDEDOR_REMOTO> TB_VENDEDOR_REMOTO { get; set; }
    }
}
