//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FILME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_FILME()
        {
            this.TB_PROGRAMA = new HashSet<TB_PROGRAMA>();
            this.TB_SESSAO_ANCINE = new HashSet<TB_SESSAO_ANCINE>();
        }
    
        public string FIL_CD_ANCINE { get; set; }
        public long DIS_CNPJ { get; set; }
        public string FIL_NM { get; set; }
        public string FIL_ID_NACIO { get; set; }
        public string FIL_DIGITAL { get; set; }
        public string FIL_GENERO { get; set; }
        public Nullable<int> FIL_CLASS_ETA { get; set; }
        public string FIL_DIRETOR { get; set; }
        public string FIL_SINOPSE { get; set; }
        public Nullable<System.DateTime> FIL_DT_INICIO { get; set; }
        public Nullable<System.DateTime> FIL_DT_FIM { get; set; }
        public Nullable<System.DateTime> FIL_ANO_LANC { get; set; }
        public string FIL_PAIS { get; set; }
        public string FIL_CD_AUX { get; set; }
        public Nullable<System.DateTime> FIL_DT_INC { get; set; }
        public Nullable<System.DateTime> FIL_DT_ALT { get; set; }
        public Nullable<System.DateTime> FIL_DT_DES { get; set; }
        public string FIL_MOT_DES { get; set; }
    
        public virtual TB_DISTRIBUIDORA TB_DISTRIBUIDORA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMA> TB_PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SESSAO_ANCINE> TB_SESSAO_ANCINE { get; set; }
    }
}
