//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GRP_CIN
    {
        public int GRP_CD { get; set; }
        public string EMP_CD_ANCINE { get; set; }
        public string GRP_NM { get; set; }
        public Nullable<System.DateTime> GRP_DT_INC { get; set; }
        public Nullable<System.DateTime> GRP_DT_ALT { get; set; }
        public Nullable<System.DateTime> GRP_DT_DES { get; set; }
        public string GRP_MOT_DES { get; set; }
    
        public virtual TB_EMPRESA_COMPLEXO TB_EMPRESA_COMPLEXO { get; set; }
    }
}
