//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SESSAO_ANCINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SESSAO_ANCINE()
        {
            this.TB_MENSAGEM_ANCINE = new HashSet<TB_MENSAGEM_ANCINE>();
            this.TB_TOT_TP_ASSENTO = new HashSet<TB_TOT_TP_ASSENTO>();
        }
    
        public long SEA_ID { get; set; }
        public long BIL_ID { get; set; }
        public string SAL_CD_ANCINE { get; set; }
        public string FIL_CD_ANCINE { get; set; }
        public System.DateTime SEA_DT_HR_INICIO { get; set; }
        public string SEA_MODAL { get; set; }
        public string SEA_FIL_NM { get; set; }
        public string SEA_FIL_TP_TELA { get; set; }
        public string SEA_FIL_DIGITAL { get; set; }
        public string SEA_FIL_TP_PROJECAO { get; set; }
        public string SEA_FIL_AUDIO { get; set; }
        public string SEA_FIL_LEG { get; set; }
        public string SEA_FIL_PRO_LIBRA { get; set; }
        public string SEA_FIL_LEG_DESC_CC { get; set; }
        public string SEA_FIL_AUDIO_DESC { get; set; }
        public long SEA_DIS_CNPJ { get; set; }
        public string SEA_DIS_NM { get; set; }
        public Nullable<long> SEA_VRE_CNPJ { get; set; }
        public string SEA_RZ_SOCIAL { get; set; }
    
        public virtual TB_BILHETERIA TB_BILHETERIA { get; set; }
        public virtual TB_FILME TB_FILME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MENSAGEM_ANCINE> TB_MENSAGEM_ANCINE { get; set; }
        public virtual TB_SALA TB_SALA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TOT_TP_ASSENTO> TB_TOT_TP_ASSENTO { get; set; }
    }
}
