//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SALA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SALA()
        {
            this.TB_BILHETERIA = new HashSet<TB_BILHETERIA>();
            this.TB_BILHETERIA1 = new HashSet<TB_BILHETERIA>();
            this.TB_BILHETERIA2 = new HashSet<TB_BILHETERIA>();
            this.TB_MENSAGEM_ANCINE = new HashSet<TB_MENSAGEM_ANCINE>();
            this.TB_PROGRAMA = new HashSet<TB_PROGRAMA>();
            this.TB_SESSAO_ANCINE = new HashSet<TB_SESSAO_ANCINE>();
        }
    
        public string SAL_CD_ANCINE { get; set; }
        public string EMP_CD_ANCINE { get; set; }
        public int SAL_NUM { get; set; }
        public string SAL_DESC { get; set; }
        public Nullable<int> SAL_QTD_LUG_PDR { get; set; }
        public Nullable<int> SAL_QTD_LUG_ESP { get; set; }
        public string SAL_SERIAL_PROJETOR { get; set; }
        public string SAL_CD_AUX { get; set; }
        public Nullable<System.DateTime> SAL_DT_INC { get; set; }
        public Nullable<System.DateTime> SAL_DT_ALT { get; set; }
        public Nullable<System.DateTime> SAL_DT_DES { get; set; }
        public string SAL_MOT_DES { get; set; }
        public string SAL_SOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BILHETERIA> TB_BILHETERIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BILHETERIA> TB_BILHETERIA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BILHETERIA> TB_BILHETERIA2 { get; set; }
        public virtual TB_EMPRESA_COMPLEXO TB_EMPRESA_COMPLEXO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MENSAGEM_ANCINE> TB_MENSAGEM_ANCINE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PROGRAMA> TB_PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SESSAO_ANCINE> TB_SESSAO_ANCINE { get; set; }
    }
}
