//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TOT_CATEG_ING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_TOT_CATEG_ING()
        {
            this.TB_TOT_MOD_PAGTO = new HashSet<TB_TOT_MOD_PAGTO>();
        }
    
        public long TCI_ID { get; set; }
        public long TTA_ID { get; set; }
        public int TCI_CAT { get; set; }
        public int TCI_QTD_ESPECT { get; set; }
    
        public virtual TB_TOT_TP_ASSENTO TB_TOT_TP_ASSENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TOT_MOD_PAGTO> TB_TOT_MOD_PAGTO { get; set; }
    }
}
