//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TOT_MOD_PAGTO
    {
        public long TMP_ID { get; set; }
        public long TCI_ID { get; set; }
        public int TMP_MOD_PAG { get; set; }
        public double TMP_VLR_ARR { get; set; }
    
        public virtual TB_TOT_CATEG_ING TB_TOT_CATEG_ING { get; set; }
    }
}
