//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USUARIO()
        {
            this.TB_PERFIL_ACESSO = new HashSet<TB_PERFIL_ACESSO>();
        }
    
        public int USU_CD { get; set; }
        public string USU_NM { get; set; }
        public string USU_LOGIN { get; set; }
        public string USU_SENHA { get; set; }
        public System.DateTime USU_DT_INC { get; set; }
        public Nullable<System.DateTime> USU_DT_ALT { get; set; }
        public Nullable<System.DateTime> USU_DT_DES { get; set; }
        public string USU_MOT_DES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PERFIL_ACESSO> TB_PERFIL_ACESSO { get; set; }
    }
}
