//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketMidia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_VENDEDOR_REMOTO
    {
        public long VRE_CNPJ { get; set; }
        public string EMP_CD_ANCINE { get; set; }
        public string VRE_RZ_SOCIAL { get; set; }
    
        public virtual TB_EMPRESA_COMPLEXO TB_EMPRESA_COMPLEXO { get; set; }
    }
}
